# Generated by Django 2.2.24 on 2021-08-30 06:51

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create time')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='update time')),
                ('status', models.SmallIntegerField(default=0, help_text='状态', verbose_name='status')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='is deleted')),
                ('goods_sn', models.CharField(default='', help_text='商品唯一货号', max_length=50, verbose_name='goods sn')),
                ('name', models.CharField(help_text='商品名', max_length=100, verbose_name='goods name')),
                ('click_num', models.IntegerField(default=0, help_text='点击数', verbose_name='goods click number')),
                ('sold_num', models.IntegerField(default=0, help_text='商品销售量', verbose_name='goods sold number')),
                ('fav_num', models.IntegerField(default=0, help_text='收藏数', verbose_name='fav number')),
                ('goods_num', models.IntegerField(default=0, help_text='库存数', verbose_name='goods num')),
                ('market_price', models.FloatField(default=0, help_text='市场价格', verbose_name='market price')),
                ('shop_price', models.FloatField(default=0, help_text='本店价格', verbose_name='goods shop price')),
                ('goods_brief', models.TextField(help_text='商品简短描述', max_length=500, verbose_name='goods brief')),
                ('goods_desc', ckeditor_uploader.fields.RichTextUploadingField()),
                ('ship_free', models.BooleanField(default=True, help_text='是否承担运费', verbose_name='ship free')),
                ('goods_front_image', models.ImageField(blank=True, help_text='封面图', null=True, upload_to='goods/cover/', verbose_name='goods front image')),
                ('is_new', models.BooleanField(default=False, help_text='是否新品', verbose_name='is new')),
                ('is_hot', models.BooleanField(default=False, help_text='是否热销', verbose_name='is hot')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create time')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='update time')),
                ('status', models.SmallIntegerField(default=0, help_text='状态', verbose_name='status')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='is deleted')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='category name')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='category code')),
                ('desc', models.TextField(default='', help_text='类别描述', verbose_name='category desc')),
                ('category_type', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], help_text='类目级别', verbose_name='category level')),
                ('navigation', models.BooleanField(default=False, help_text='是否导航', verbose_name='navigation')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父类目级别', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.GoodsCategory')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
                'db_table': 'goods_category',
            },
        ),
        migrations.CreateModel(
            name='HotSearchWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create time')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='update time')),
                ('status', models.SmallIntegerField(default=0, help_text='状态', verbose_name='status')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='is deleted')),
                ('keywords', models.CharField(default='', help_text='热搜词', max_length=20, verbose_name='keyword')),
                ('index', models.IntegerField(default=0, help_text='排序', verbose_name='order')),
            ],
            options={
                'verbose_name': '热搜词',
                'verbose_name_plural': '热搜词',
                'db_table': 'goods_hot_word',
            },
        ),
        migrations.CreateModel(
            name='IndexAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create time')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='update time')),
                ('status', models.SmallIntegerField(default=0, help_text='状态', verbose_name='status')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='is deleted')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
            options={
                'verbose_name': '首页商品类别广告',
                'verbose_name_plural': '首页商品类别广告',
                'db_table': 'index_ad',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create time')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='update time')),
                ('status', models.SmallIntegerField(default=0, help_text='状态', verbose_name='status')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='is deleted')),
                ('image', models.ImageField(blank=True, help_text='图片', null=True, upload_to='goods/image/', verbose_name='goods image')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'db_table': 'goods_image',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create time')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='update time')),
                ('status', models.SmallIntegerField(default=0, help_text='状态', verbose_name='status')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='is deleted')),
                ('name', models.CharField(default='', help_text='品牌名', max_length=30, verbose_name='brand name')),
                ('desc', models.TextField(default='', help_text='品牌描述', max_length=200, verbose_name='brand desc')),
                ('image', models.ImageField(help_text='品牌图片', max_length=200, upload_to='brands/')),
                ('category', models.ForeignKey(blank=True, help_text='商品类目', null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'db_table': 'goods_brand',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(help_text='商品类目', on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create time')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='update time')),
                ('status', models.SmallIntegerField(default=0, help_text='状态', verbose_name='status')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='is deleted')),
                ('image', models.ImageField(upload_to='goods/banner/', verbose_name='轮播图片')),
                ('index', models.IntegerField(default=0, verbose_name='轮播顺序')),
                ('goods', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
            options={
                'verbose_name': '轮播商品',
                'verbose_name_plural': '轮播商品',
                'db_table': 'goods_banner',
            },
        ),
    ]
