# Generated by Django 2.2.24 on 2022-06-22 16:49

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(help_text='用户头像', storage=django_minio_backend.models.MinioBackend(bucket_name='dailyfresh-media-bucket'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='邮箱', max_length=128, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='姓名', max_length=30, null=True, verbose_name='username'),
        ),
    ]
