# Generated by Django 2.2.24 on 2021-08-30 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create time')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='update time')),
                ('status', models.SmallIntegerField(default=0, help_text='状态', verbose_name='status')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='is deleted')),
                ('nums', models.IntegerField(default=0, help_text='购买数量', verbose_name='shop number')),
                ('goods', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'shop_car',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create time')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='update time')),
                ('status', models.SmallIntegerField(default=0, help_text='状态', verbose_name='status')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='is deleted')),
                ('order_sn', models.CharField(blank=True, help_text='订单号', max_length=30, null=True, unique=True, verbose_name='order sn')),
                ('trade_no', models.CharField(blank=True, help_text='交易号', max_length=100, null=True, unique=True, verbose_name='trade no')),
                ('pay_status', models.CharField(choices=[('TRADE_SUCCESS', '成功'), ('TRADE_CLOSED', '超时关闭'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_FINISHED', '交易结束'), ('paying', '待支付')], default='paying', help_text='订单状态', max_length=30, verbose_name='pay status')),
                ('post_script', models.CharField(help_text='订单留言', max_length=200, verbose_name='post script')),
                ('order_mount', models.FloatField(default=0.0, help_text='订单金额', verbose_name='order mount')),
                ('pay_time', models.DateTimeField(blank=True, help_text='支付时间', null=True, verbose_name='pay time')),
                ('address', models.CharField(default='', help_text='收货地址', max_length=100, verbose_name='address')),
                ('signer_name', models.CharField(default='', help_text='签收人', max_length=20, verbose_name='signer name')),
                ('singer_mobile', models.CharField(help_text='联系电话', max_length=11, verbose_name='singer mobile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'shop_order',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create time')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='update time')),
                ('status', models.SmallIntegerField(default=0, help_text='状态', verbose_name='status')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='is deleted')),
                ('goods_num', models.IntegerField(default=0, help_text='商品数量', verbose_name='goods number')),
                ('goods', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
                ('order', models.ForeignKey(help_text='订单信息', on_delete=django.db.models.deletion.CASCADE, to='shop.OrderInfo')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
                'db_table': 'shop_goods',
            },
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'goods'), name='unique goods user'),
        ),
    ]
